---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mealie

resources:
  - pvc.yaml
  - deployment.yaml
  - svc.yaml
  - ingress.yaml

configMapGenerator:
  - name: mealie-config
    envs:
      - config.env
